### ISSUE TITLE
Move the common keys to top in secrets.yml across all neeto apps

### ISSUE THREAD

**Issue by prasanthchaduvula** [bigbinary/neeto-compliance#199]
except neetoDesk, neetoPopups and neetoForm
`asset_host: <%= ENV["ASSET_HOST"] %>`

Present in all environments with different values
```
secret_key_base
devise:
    secret_key:
```

Present in all apps key is same but value changes
```
server_port: 9012
client_app_name: "Quiz"
website_url: "https://neeto.com/neetochangelog"
```

Present in half apps
```
heroku_app_name: <%= ENV["HEROKU_APP_NAME"] %>
support_email: support@neetoinvoice.com
client_authorization_token: <%= ENV["CLIENT_AUTHENTICATION_TOKEN"] %>
attr_encrypted:
    encryption_key: <%= ENV['ATTR_ENCRYPTION_KEY'] %>
```
Present in 90% apps
```
sidekiq:
    username: <%= ENV['SIDEKIQ_USERNAME'] %>
    password: <%= ENV['SIDEKIQ_PASSWORD'] %>
```

Present in all apps but signup_path: "/signups/new" not present in 5 apps and in neetoChat except the URL nothing present
```
auth_app:
    url: <%= ENV["AUTH_APP_URL"] %>
    id: <%= ENV["AUTH_APP_ID"] %>
    secret: <%= ENV["AUTH_APP_SECRET"] %>
    signup_path: "/signups/new"
```
